# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-02 00:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20170930_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 2, 0, 37, 16, 488184, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
