# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_business_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IssueDate', models.DateField(verbose_name='Invoice Date')),
                ('To', models.CharField(max_length=500, verbose_name='Customer')),
                ('BillingAddress', models.CharField(max_length=200, verbose_name='Billing Address')),
                ('DueDateType', models.CharField(choices=[('Net', 'Net'), ('By', 'By')], max_length=3, verbose_name='Due Date')),
                ('InvoiceSummary', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200, verbose_name='Description')),
                ('TaxCode', models.CharField(max_length=200, verbose_name='Tax')),
                ('Qty', models.FloatField(verbose_name='Quantity')),
                ('Item', models.CharField(max_length=200, verbose_name='Item')),
                ('Amount', models.FloatField(verbose_name='Amount')),
            ],
        ),
    ]
