# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-09 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_salesinvoice_salesinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='SalesInvoice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.SalesInvoice'),
            preserve_default=False,
        ),
    ]
