# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-24 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingbuddy', '0010_sendmails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Enter Appointment Date/ Time')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('request_closed', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=50, verbose_name='Request Status')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_reason', models.CharField(max_length=200, verbose_name='Support Type')),
            ],
        ),
        migrations.AddField(
            model_name='support_request',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingbuddy.SupportTypes'),
        ),
        migrations.AddField(
            model_name='support_request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
