# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-19 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accountingbuddy', '0012_advert'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopActivationReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('MAC', 'MAC'), ('WINDOWS', 'WINDOWS'), ('UBUNTU', 'UBUNTU')], max_length=200, verbose_name='Select System')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
