# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-12-31 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountingbuddy', '0013_desktopactivationreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('businessFile', models.FileField(upload_to='BusinessTypeFiles')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Type of Business, Service, Manufacturing, Trading,Doctor etc', max_length=200, verbose_name='Business Type')),
            ],
        ),
        migrations.AddField(
            model_name='businesstypefile',
            name='businesstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountingbuddy.BusinessTypes'),
        ),
    ]
